// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace LockersHub.DALS.Entities
{
    public partial class LockersDBContext : IdentityDbContext<AspNetUser, AspNetRole, string>
    {
        public LockersDBContext()
        {
        }

        public LockersDBContext(DbContextOptions<LockersDBContext> options)
            : base(options)
        {
        }

        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Locker> Lockers { get; set; }
        public virtual DbSet<State> States { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<City>(entity =>
            {
                entity.HasOne(d => d.StateCodeNavigation)
                    .WithMany(p => p.Cities)
                    .HasForeignKey(d => d.StateCode)
                    .HasConstraintName("FK_Cities_States");
            });

            modelBuilder.Entity<Locker>(entity =>
            {
                entity.HasOne(d => d.City)
                    .WithMany(p => p.Lockers)
                    .HasForeignKey(d => d.CityId)
                    .HasConstraintName("FK_Lockers_Cities");
            });

            modelBuilder.Entity<State>(entity =>
            {
                entity.HasOne(d => d.CountryCodeNavigation)
                    .WithMany(p => p.States)
                    .HasForeignKey(d => d.CountryCode)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_States_Countries");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        void OnModelCreatingPartial(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
        }
    }
}