// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LockersHub.DALS.Entities
{
    public partial class Locker
    {
        [Key]
        public int LockerId { get; set; }
        [Required]
        [StringLength(150)]
        public string Name { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal Price { get; set; }
        [StringLength(350)]
        public string Description { get; set; }
        [StringLength(50)]
        public string Size { get; set; }
        public int? QuantityAvailable { get; set; }
        [StringLength(4)]
        public string StateCode { get; set; }
        public int? CityId { get; set; }
        [StringLength(150)]
        public string ImageUrl { get; set; }
        [StringLength(15)]
        public string Status { get; set; }
        [StringLength(450)]
        public string CreatedBy { get; set; }
        [StringLength(450)]
        public string ModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateCreated { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateModified { get; set; }

        [ForeignKey(nameof(CityId))]
        [InverseProperty("Lockers")]
        public virtual City City { get; set; }
    }
}