// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LockersHub.BL.DVM
{
    public partial class AspNetUserRoleDVM
    {
        [Key]
        public string UserId { get; set; }
        [Key]
        public string RoleId { get; set; }


        public virtual AspNetRoleDVM Role { get; set; }
        public virtual AspNetUserDVM User { get; set; }
    }
}