// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LockersHub.BL.DVM
{
    public partial class LockerDVM
    {
        [Key]
        public int LockerId { get; set; }
        [Required]
        [StringLength(150)]
        public string Name { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal Price { get; set; }
        [StringLength(350)]
        public string Description { get; set; }
        public int? QuantityAvailable { get; set; }
        [StringLength(4)]
        public string StateCode { get; set; }
        public int? CityId { get; set; }
        [StringLength(15)]
        public string Status { get; set; }

        public virtual CityDVM City { get; set; }
    }
}