// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LockersHub.BL.DVM
{
    public partial class StateDVM
    {
        [Key]
        [StringLength(4)]
        public string Code { get; set; }
        [Required]
        [StringLength(100)]
        public string Name { get; set; }
        [Required]
        [StringLength(4)]
        public string CountryCode { get; set; }

        public virtual CountryDVM CountryCodeNavigation { get; set; }
        public virtual ICollection<CityDVM> Cities { get; set; }
    }
}